[package]
name = "ntp_project"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
pollster = "0.4.0"
rand = "0.9.2"
rayon = "1.11.0"
serde_json = "1.0.145"

[[bin]]
name = "ntp_project"
path = "main.rs"
